title: Syed Salman Bacha
logo: assets/profile-pic (4).png
description: Enthusiast Data Analyst fueled by passion, finding joy in analysis, coding, reading, and critical thinking. Driven by 
the firm conviction that diligent efforts pave the path to achieving one's aspirations
show downloads: true
theme: jekyll-theme-minimal
