title: Syed Salman Bacha
logo: assets/profile-pic (4).png
description: Enthusiast Data Analyst fueled by passion, finding joy in analysis, coding, reading, and critical thinking. 
show downloads: true
theme: jekyll-theme-minimal
